### ISSUE TITLE
Fill jira for the `-DBUILD_BINDINGS=python,python3` problem

### ISSUE THREAD

**Issue by jiridanek** [jiridanek/qpid-proton#5]

**Comment by jiridanek** [comment]
Do you want my help with this? Submitting a new Jira ticket should be fairly quick... esp. soon after you encountered the issue, while you remember the reproduction steps.

**Comment by SudhanAruna** [comment]
Sorry for this late reply. Yes, I'm not sure what I should fill for certain fields  Hoping to discuss it in the next call

**Comment by jiridanek** [comment]
@SudhanAruna Right. My advice would be: "Put in steps to reproduce the problem, into the large text field. Everything else is optional and we can add the details later together. It is perfectly OK to submit incomplete ticket, as long as the steps to reproduce the problem are filled."

**Comment by SudhanAruna** [comment]
I have created an issue. Link : https://issues.apache.org/jira/projects/PROTON/issues/PROTON-2391?filter=allopenissues. Please let me know if I should modify anything.

**Comment by jiridanek** [comment]
Looks correct to me, just two small additions:

1. Set "Affects version/s" to `Proton-c-0.34.0`. I know it affects the latest released version, so that is the best version to set there. (If the bug only happens on main branch, then I usually set the upcoming release version here, but that is only my personal convention)
2. Mention that the correct separator is a `;`. So that your reproduction steps are actually requesting a single binding named `python,something` to be built. Say that docs for the option are needed.

**Comment by jiridanek** [comment]
Nice. Let's close it here as done.
