### ISSUE TITLE
GitHub Actions CI fails with `ModuleNotFoundError: No module named 'cproton'`

### ISSUE THREAD

**Issue by jiridanek** [jiridanek/qpid-proton#7]
```
11: ======================================================================
11: ERROR: test_message (unittest.loader._FailedTest)
11: ----------------------------------------------------------------------
11: ImportError: Failed to import test module: test_message
11: Traceback (most recent call last):
11:   File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
11:     module = self._get_module_from_name(name)
11:   File "/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
11:     __import__(name)
11:   File "/home/runner/work/qpid-proton/qpid-proton/python/tests/proton_tests/test_message.py", line 25, in <module>
11:     from proton import *
11:   File "/home/runner/work/qpid-proton/qpid-proton/python/proton/__init__.py", line 35, in <module>
11:     from cproton import PN_VERSION_MAJOR, PN_VERSION_MINOR, PN_VERSION_POINT
11: ModuleNotFoundError: No module named 'cproton'
```

**Comment by SudhanAruna** [comment]
@jiridanek I tried changing the LD_LIBRARY_PATH to `/home/runner/work/qpid-proton/qpid-proton/INSTALL/lib` and it didn't work.
path before changing was ` /opt/hostedtoolcache/Python/3.6.13/x64/lib`. How can I fix this CI issue?

**Comment by jiridanek** [comment]
@SudhanAruna You aren't building the cproton module, because we deleted the SWIG building code form the project in PR #3 ;P

Tell me what you would do now, and I will also share some ideas. We will figure out something which will let the CI run and will not mean too much work upfront for you.

**Comment by jiridanek** [comment]
Anyways, don't worry about install at all (yet). The tests run from the build directory, they don't need make install. (Or they shouldn't need it)

**Comment by jiridanek** [comment]
Yeah, that PR is one possible fix. Another one would be to do `sudo python3 -m pip install --user python-qpid-proton` in a CI job. Let the tests that were not yet updated simply use Proton from PyPI :p And yet another option would be to put everything the code needs into your cdef and import it through CFFI, so that you don't need swig any more; but that might require lots of work upfront.

**Comment by SudhanAruna** [comment]
Yes, using this approach we can move one by one to using CFFI.
